# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:7.0 as base
WORKDIR /stac2mqtt

# Set environment variable for development
ENV ASPNETCORE_ENVIRONMENT=Development

# Expose the debug port
EXPOSE 5000

# copy everything else and build app
COPY . .

RUN dotnet restore

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]
